name: manual_workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: display content
        run: echo "Hello world"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: display content
        run: echo "Hello jaga"
