name: manual_workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: calling secret var
        run: echo "Hi my name is ${{var.user_name}} and here is the ${{secrets.password}}"


        
